# Generated by Django 5.1.7 on 2025-03-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.IntegerField(default=0)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=300, null=True),
                ),
                (
                    "big_description",
                    models.TextField(
                        blank=True, default="", max_length=1000, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomapp.category",
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "ordering": ["name"],
            },
        ),
    ]
