# Generated by Django 5.1.7 on 2025-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0002_alter_category_name_alter_product_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=0, upload_to="image"),
            preserve_default=False,
        ),
    ]
