# Generated by Django 5.1.7 on 2025-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0005_alter_cart_pid_alter_cart_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
