# Generated by Django 5.1.7 on 2025-03-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0006_category_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="qty",
        ),
        migrations.AddField(
            model_name="cart",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
